- name: Install lib for jenkins ansible
  pip:
    name:
    - python-jenkins
    - lxml

- name: Install plugin for Jenkins without authentication
  jenkins_plugin:
    name: "{{ item }}"
    # url: http://localhost:8080
    state: latest
  with_items:
    - workflow
    - workflow-job
    - workflow-scm-step
    - workflow-aggregator
    - pipeline
    - pipeline-stage-view
    # - pipeline-input-step
    # - pipeline-model-api
    # - pipeline-model-declarative-agent
    # - pipeline-rest-api
    - build-pipeline-plugin
    - git
    - checkstyle
    - pmd
    - dashboard-view
    - warnings-ng
    - timestamper
    - copyartifact
    # - git-client
    - github
    - warnings
    - ws-cleanup
    # - workflow-support
    # - job-dsl
    - scm-api


- name: Restart Jenkins service
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: "200"
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
    'status' in jenkins_service_status and
    jenkins_service_status['status'] == 200

- name: Create a jenkins job without authentication
  jenkins_job:
    config: "{{ lookup('file', 'jobs/job.xml') }}"
    name: EP-tsk
    url: http://localhost:8080

- name: Create a jenkins job without authentication
  jenkins_job:
    config: "{{ lookup('file', 'jobs/deploy_wp.xml') }}"
    name: Deploy_wordpress
    url: http://localhost:8080

- name: Create a jenkins job without authentication
  jenkins_job:
    config: "{{ lookup('file', 'jobs/check_conf.xml') }}"
    name: Checkout_configs
    url: http://localhost:8080


- name: script for webhook
  shell: |
    chmod +x /vagrant/scripts/webhook.sh
    sh /vagrant/scripts/webhook.sh
    exit 0
