- name: Install lib for jenkins ansible
  pip:
    name:
    - python-jenkins
    - lxml
    - docker

- name: Install plugin for Jenkins without authentication
  jenkins_plugin:
    name: "{{ item }}"
    # url: http://localhost:8080
    state: latest
  with_items:
    - workflow
    - workflow-job
    - workflow-scm-step
    - pipeline
    # - pipeline-stage-view
    - build-pipeline-plugin
    - git
    - timestamper
    - github
    - ws-cleanup
    - workflow-aggregator
    - scm-api


- name: Restart Jenkins service
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: "200"
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
    'status' in jenkins_service_status and
    jenkins_service_status['status'] == 200

- name: Create a jenkins job Deploy_wordpress
  jenkins_job:
    config: "{{ lookup('file', 'jobs/deploy_wp.xml') }}"
    name: Deploy_wordpress
    url: http://localhost:8080

- name: Create a jenkins job Checkout_configs
  jenkins_job:
    config: "{{ lookup('file', 'jobs/check_conf.xml') }}"
    name: Checkout_configs
    url: http://localhost:8080

- name: Create a jenkins job Deploy_Wordpress_with_ansible
  jenkins_job:
    config: "{{ lookup('file', 'jobs/wp_ansible.xml') }}"
    name: Deploy_Wordpress_with_ansible
    url: http://localhost:8080

- name: chmod for our script webhook
  file:
    path: /vagrant/scripts/webhook.sh
    state: touch
    mode: u+x,g+x,o+x

- name: Script for webhook
  shell: /vagrant/scripts/webhook.sh
