
- name: Install required jenkins packages
  yum:
    name: "{{ item }}"
  loop: ['wget', 'java-1.8.0-openjdk', 'git', 'python-pip']


- name: Import Jenkins key and download jenkins.repo
  yum_repository:
    name: jenkins
    state: present
    description: Official Jenkins Yum Repo
    baseurl: http://pkg.jenkins.io/redhat
    gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    gpgcheck: yes
    enabled: yes

- name: Install service Jenkins from repository
  yum :
    name: jenkins
    update_cache: yes
    state: present
