---
- name: Install and start Jenkins
  hosts: localhost

  become: yes
  gather_facts: yes

  tasks:
  - name: install python 2
    raw: which python || (apt -y update && apt install -y python-minimal)
    when: ansible_os_family == 'Debian'

  - name: install python 2
    raw: which python || (yum -y update && yum install -y python-minimal)
    when: ansible_os_family == 'RedHat'

  - name: Set timezone to Europe/Minsk
    timezone:
      name: Europe/Minsk

  - name: Create a directory if it does not exist
    file:
      path: /wordpress
      state: directory
      mode: '0777'

  - include_role:
      name: docker

  - include_role:
      name: jenkins
